	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace NASDMS.RDS
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 3/23/2017 12:04:07 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// NASDMS Unit-of-Work

	public partial class NASDMSUnitOfWork : UnitOfWork
	{
		public NASDMSUnitOfWork() : base(new NASDMSDb()) { }
	}
}
